# Generated by Django 4.2.20 on 2025-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_alter_users_options_users_company_users_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('diseñador', 'Diseñador'), ('vendedor', 'Vendedor'), ('gerente', 'Gerente')], default='cliente', max_length=50),
        ),
    ]
