# Generated by Django 5.2 on 2025-04-22 23:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idorder', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.IntegerField()),
                ('url_download', models.URLField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppCart',
            fields=[
                ('idshoppcart', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('idorderdetails', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_control.order')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_control.product')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('idreviews', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_control.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppCartDetails',
            fields=[
                ('idshoppcartdetails', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_control.product')),
                ('idshoppcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_control.shoppcart')),
            ],
        ),
    ]
