# Generated by Django 5.2 on 2025-08-05 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='idcategory',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='brand_control.category'),
        ),
    ]
