# Generated by Django 5.2 on 2025-08-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_control', '0001_initial'),
    ]

    operations = [
        # Hacer que category_id sea nullable
        migrations.RunSQL(
            "ALTER TABLE brand_control_product MODIFY COLUMN category_id bigint NULL;",
            reverse_sql="ALTER TABLE brand_control_product MODIFY COLUMN category_id bigint NOT NULL;"
        ),
    ]
