# Generated by Django 5.2 on 2025-10-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_control', '0003_project_servicecategory_service_quoterequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_messages/'),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
