# Generated by Django 5.2 on 2025-08-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_control', '0002_rename_idcategory_category_id_and_more'),
        ('brand_control', '0003_auto_20250805_1604'),
    ]

    operations = [
    ]
