# Generated by Django 5.2 on 2025-08-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_control', '0004_merge_20250805_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
