# Generated by Django 5.2 on 2025-10-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_control', '0004_projectmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('quote', 'Quote'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('payment_pending', 'Payment Pending'), ('in_progress', 'In Progress'), ('review', 'Review'), ('pending_completion_confirmation', 'Pending Completion Confirmation'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='quote', max_length=35),
        ),
    ]
