# Generated by Django 5.2 on 2025-10-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_control', '0005_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppcartdetails',
            name='idshoppcart',
        ),
        migrations.RemoveField(
            model_name='shoppcartdetails',
            name='idproduct',
        ),
        migrations.DeleteModel(
            name='ShoppCart',
        ),
        migrations.DeleteModel(
            name='ShoppCartDetails',
        ),
    ]
