# Generated by Django 5.2 on 2025-10-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_control', '0006_remove_shoppcart_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='idorder',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='idproduct',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='idproduct',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
